-- Bug: ketika mengonfirmasi pembayaran pending (dari extend session) dengan uang tunai
-- lebih besar dari total yang harus dibayar, kembalian selalu tertulis 0.
-- Root cause: "__SP__ConfirmExtendPayment" hanya mengubah payment_status menjadi 'paid'
-- tanpa pernah menerima/menghitung uang tunai (cash_received) & kembalian (change_amount)
-- pada saat konfirmasi. Nilai cash_received/change_amount yang tersimpan hanyalah nilai
-- lama (dari saat ExtendSession dibuat dengan p_pay_now=false, biasanya 0).
--
-- Fix:
-- 1. "__SP__ConfirmExtendPayment" sekarang menerima parameter opsional p_cash_received.
--    Jika diisi, sistem akan memvalidasi cukup/tidaknya uang tunai dan menghitung ulang
--    cash_received & change_amount sesuai pembayaran yang sebenarnya terjadi saat konfirmasi.
-- 2. Fungsi baru "__SP__ConfirmSessionPendingPayments" ditambahkan untuk kasus umum di kasir:
--    melunasi SEMUA pembayaran pending milik satu sesi sekaligus dengan SATU nilai uang
--    tunai (misal 2 tagihan pending @4000 = 8000, dibayar tunai 10000 => kembalian 2000).

CREATE OR REPLACE FUNCTION "__SP__ConfirmExtendPayment"(p_payment_id UUID, p_cash_received NUMERIC DEFAULT NULL) RETURNS TABLE(payment_id UUID, payment_status VARCHAR, paid_at TIMESTAMPTZ, total_payment NUMERIC, cash_received NUMERIC, change_amount NUMERIC) LANGUAGE plpgsql AS $$ DECLARE v_payment payments%ROWTYPE; v_now TIMESTAMPTZ:=NOW(); v_pending BIGINT; v_console_id UUID; v_cash NUMERIC(10,2); v_change NUMERIC(10,2); BEGIN SELECT * INTO v_payment FROM payments WHERE payments.id=p_payment_id FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'PAYMENT_NOT_FOUND'; END IF; IF v_payment.payment_status!='pending' THEN RAISE EXCEPTION 'PAYMENT_NOT_PENDING'; END IF; IF p_cash_received IS NOT NULL THEN IF p_cash_received<v_payment.total_payment THEN RAISE EXCEPTION 'INSUFFICIENT_CASH: butuh Rp %.0f',v_payment.total_payment; END IF; v_cash:=p_cash_received; v_change:=p_cash_received-v_payment.total_payment; ELSE v_cash:=v_payment.cash_received; v_change:=v_payment.change_amount; END IF; UPDATE payments SET payment_status='paid',paid_at=v_now,cash_received=v_cash,change_amount=v_change,updated_at=v_now WHERE payments.id=p_payment_id; SELECT COUNT(*) INTO v_pending FROM payments WHERE payments.session_id=v_payment.session_id AND payments.payment_status='pending'; IF v_pending=0 THEN SELECT s.console_id INTO v_console_id FROM sessions s WHERE s.id=v_payment.session_id; IF v_console_id IS NOT NULL THEN UPDATE tv_notifications SET is_active=false,updated_at=v_now WHERE title='Pembayaran Tertunda' AND is_active=true AND (target_all=true OR target_console_ids::jsonb@>to_jsonb(v_console_id::TEXT)); END IF; END IF; RETURN QUERY SELECT p_payment_id,'paid'::VARCHAR,v_now,v_payment.total_payment,v_cash,v_change; END; $$;

CREATE OR REPLACE FUNCTION "__SP__ConfirmSessionPendingPayments"(p_session_id UUID, p_cash_received NUMERIC) RETURNS TABLE(session_id UUID, confirmed_count INT, total_paid NUMERIC, cash_received NUMERIC, change_amount NUMERIC) LANGUAGE plpgsql AS $$ DECLARE v_total NUMERIC(10,2); v_count INT; v_change NUMERIC(10,2); v_now TIMESTAMPTZ:=NOW(); v_last_payment_id UUID; v_console_id UUID; BEGIN PERFORM 1 FROM payments WHERE payments.session_id=p_session_id AND payments.payment_status='pending' FOR UPDATE; SELECT COALESCE(SUM(total_payment),0),COUNT(*) INTO v_total,v_count FROM payments WHERE payments.session_id=p_session_id AND payments.payment_status='pending'; IF v_count=0 THEN RAISE EXCEPTION 'NO_PENDING_PAYMENT'; END IF; IF p_cash_received<v_total THEN RAISE EXCEPTION 'INSUFFICIENT_CASH: butuh Rp %.0f',v_total; END IF; v_change:=p_cash_received-v_total; UPDATE payments SET payment_status='paid',paid_at=v_now,cash_received=total_payment,change_amount=0,updated_at=v_now WHERE payments.session_id=p_session_id AND payments.payment_status='pending'; SELECT id INTO v_last_payment_id FROM payments WHERE payments.session_id=p_session_id AND payments.payment_status='paid' ORDER BY paid_at DESC,created_at DESC LIMIT 1; UPDATE payments SET cash_received=p_cash_received,change_amount=v_change,updated_at=v_now WHERE payments.id=v_last_payment_id; SELECT s.console_id INTO v_console_id FROM sessions s WHERE s.id=p_session_id; IF v_console_id IS NOT NULL THEN UPDATE tv_notifications SET is_active=false,updated_at=v_now WHERE title='Pembayaran Tertunda' AND is_active=true AND (target_all=true OR target_console_ids::jsonb@>to_jsonb(v_console_id::TEXT)); END IF; RETURN QUERY SELECT p_session_id,v_count,v_total,p_cash_received,v_change; END; $$;
